name: Build & Deploy Flutter Web

on:
  push:
    branches: [main]
  workflow_dispatch:  # Permet de déclencher manuellement depuis GitHub

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --base-href /

      - name: Copy CNAME into build output
        run: echo "upyourdeen.com" > build/web/CNAME

      - name: Copy preview image into build output
        run: cp preview.jpg build/web/preview.jpg

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: false
